version: "3.9"

services:
  backend:
    container_name: backend
    image: deno-app-image
    restart: always
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    image: next-app-image
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:3000
